### ISSUE TITLE
About batch_size of ConvGRU

### ISSUE THREAD

**Issue by t13m** [EderSantana/seya#17]
Hi, I'm using ConvGRU of seya doing some experiments, and here is my question, why there must be a `batch_size` in ConvGRU.__init__()? Is there any way to create an instance of ConvGRU without knowing `batch_size`?

**Comment by EderSantana** [comment]
Its mainly to support both Theano and TF backend. TensorFlow doesn't know how to reshape things without having explicit batch sizes. 

But, if that is crucial for you work, you can try to modify the code to use Theano.repeat and Theano.reshape using symbolic values. When TF learns how to handle symbolic resize, I'll update the code.

I made it this way so that ConvGRU could be pushed to Keras main repo at one point.
